### ISSUE TITLE
Clockwise and counter clockwise prop

### ISSUE THREAD

**Issue by Gunrunner101** [SV-Seeker/Mor-Go-Thruster#1]
First, I want to thank you Drew for your work modifying Ole thruster design. I am very pleased with the additional support added. I am working on a ROV myself, unlike the SVSeeker towed design, mine will be using 6 thrusters in a more traditional style ROV, 2 fore, 2 aft, 1 port side and 1 starboard side. 

Now to my question/request. Rotational forces (from the props spinning) are not a concern with the SVSeeker ROV design, but are certainly a problem with traditional designs. I am pretty brutal at using Autodesk Inventor and was hoping you would release a reverse prop design to help all the users looking to use your thruster in traditional ROV build. 

If you do not have time for this, any direction would be much appreciated. 

With Respect,
Andrew

**Comment by drewtm** [comment]
Thanks for the comment Andrew. As we discussed just now, you can get the required clockwise or counterclockwise propeller by mirroring the STL file. I'll make a note of this in the README.
